### ISSUE TITLE
Data Job List error

### ISSUE THREAD

**Issue by schefs26** [pg-dev-git/tcrm_toolkit#1]
Error when running 'List All Jobs by Status'

![image](https://user-images.githubusercontent.com/44069400/115960513-d7cb0180-a4df-11eb-8d7e-f5ee55eed930.png)

**Comment by pg-dev-git** [comment]
Interesting. Seems like some jobs have a different parameter than "executedDate". I will post a new release that contains a handle for that. Thanks!

Try using Windows Terminal. Looks much better

**Comment by pg-dev-git** [comment]
I just published a new release with fixes. Thanks!
